#!/bin/bash
#
# Copyright 2014 Emil Lundberg <lundberg.emil@gmail.com>. All rights reserved.
#
# This file is part of passqr.
#
# passqr is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# passqr is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# passqr. If not, see <http://www.gnu.org/licenses/>.

GETOPT=getopt
PROGRAM="$(basename "$0")"
CONFIG=(
    '/etc/passqr.conf'
    "${HOME}/.config/passqr.conf"
)

PIXELSIZE=6
TIMEOUT=3
VERBOSE=false
VIEWER_EXEC='display -'

ARGS="$($GETOPT -o c:t:v -l config:,timeout:,verbose -n "$PROGRAM" -- "$@")"
if [[ $? -ne 0 ]]; then
    echo "Usage: ${PROGRAM} [-t,--timeout SECONDS] [-v,--verbose] PASS_PATH"
    exit 1
fi

eval set -- "$ARGS"
while true; do
    case $1 in
        -c|--config)
            shift
            CONFIG+=("$1")
            ;;
        -t|--timeout)
            shift
            TIMEOUT=$1
            ;;
        -v|--verbose)
            VERBOSE=true
            ;;
        --)
            shift
            break
            ;;
    esac
    shift
done

for config_file in "${CONFIG[@]}"; do
    if [[ -f "$config_file" ]]; then
        if $VERBOSE; then
            echo "Sourcing config file ${config_file}"
        fi
        source "$config_file"
    fi
done

pass_cmd="pass show $@"
if output=$($pass_cmd); then
    if $VERBOSE; then
        echo "Encoding first line of output of '${pass_cmd}'"
    fi
    output=$(echo "$output" | head -n1)
    qrencode -s $PIXELSIZE -t PNG -o - "$output" | $VIEWER_EXEC - &
    sleep $TIMEOUT
    kill $! 2>/dev/null
fi
